config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  
  get   '/uploads/mysubmission', to: 'uploads#mysubmission'
  get   '/uploads/sharedtome', to: 'uploads#sharedToMe'
  get   '/uploads/search', to: 'uploads#search'
  #post  '/uploads/search', to: 'uploads#search'
  get   '/uploads/search(.:format)', to: 'uploads#search'
  post  '/uploads/search(.:format)', to: 'uploads#search'


  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :uploads, only: [:new, :create, :update, :destroy, :show, :index, :edit]

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :user
  has_many :images, :dependent => :destroy
  before_save :destroy_image?
  
  has_many :tags, :dependent => :destroy
  has_many :protections, :dependent => :destroy
  accepts_nested_attributes_for :images , :allow_destroy => true,  :reject_if => lambda { |a| a[:image].blank? } 
  accepts_nested_attributes_for :tags, :allow_destroy => true, :reject_if => lambda { |a| a[:tagname].blank? }
  accepts_nested_attributes_for :protections, :reject_if => lambda { |a| a[:sharedid].blank? }, :allow_destroy => true
  
  PERMISSIONS = ['Public', 'Private', 'Protected']

  default_scope -> { order(created_at: :desc) }
  
  
  def image_delete
    @image_delete ||= "0"
  end

 def image_delete=(value)
   @image_delete = value
 end

private
   def destroy_image?
    self.images.clear if @image_delete == "1"
   end
  
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :logged_in_user
  layout "something"

  def index
    @uploads = Upload.all
  end

  def show
    @upload = Upload.find(params[:id])
  end

  def new
    @upload = Upload.new
    #@upload.images.build
    6.times {@upload.tags.build}
    3.times {@upload.protections.build}
    
  end

  def edit
    @upload = Upload.find(params[:id])
  end


  def create
    @upload = current_user.uploads.build(upload_params)
    if @upload.save
      flash[:success] = "Upload was successfully created!"
      redirect_to @upload
    else
      render 'uploads_url'
    end

  end


  def update
    @upload = Upload.find(params[:id])
    if @upload.update_attributes(upload_params)
      flash[:success] = "Submission is updated"
      redirect_to @upload
    else
      render 'edit'
    end
  end

  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
    def mysubmission
    @all_submission = current_user.uploads.all
    end
  
  def sharedToMe
    data = Array.new
    data = Protection.pluck(:sharedid,:upload_id)

    previous_upid = 0
    @shared = Array.new
    data.each do |(email, upid)|
      if email == current_user.email && previous_upid != upid
        @shared << upid
        previous_upid = upid
      end
    end

  end
  
  def search
   #@datas = Upload.where(permission: "Public")
    if params[:search]
      @tags = Tag.search(params[:search]).order("created_at DESC")
      @ids = @tags.pluck(:upload_id)
    end
  end
  
  
  private

    def upload_params
      params.require(:upload).permit(:id, :description, :permission, :url, :image_delete, 
                     images_attributes: [:id, :image], tags_attributes: [:id, :tagname], protections_attributes: [:id, :sharedid])
    end
    
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
  
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.erb
<%= form_for(@upload) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/_upload.html.erb
<li id="upload-<%= upload.id %>">
  <span class="user"><%= link_to upload.user.name, upload.user %></span>
  <span class="image"><%= image_tag upload.image(:small) %></span>
  <span class="description"><%= upload.description %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(upload.created_at) %> ago.
  </span>
</li>

app/views/uploads/edit.html.erb
<% provide(:title, "Edit upload") %>
<h1 style="margin-left:226px;">Update this upload</h1>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <%= form_for(@upload) do |f| %>

      <% if @upload.images.first %>
        <% @upload.images.all.each do |b| %>
          <%= image_tag b.image(:small) %>
        <% end %>
        <br><br>
        <h4> If you want remove all images, Check here <%= f.check_box :image_delete %> </h4>
        <br>
        <h4> If you want add additional images, include below </h4>
        <%= f.file_field @upload.images.build, multiple: true, name: "upload[images_attributes][][image]", class: 'form-control' %>
      <% else %>
        <%= f.file_field @upload.images.build, multiple: true, name: "upload[images_attributes][][image]", class: 'form-control' %>
      <% end %>
      <br>

      
        <%= f.label :tags, "Tags" %> 
        <br>
        <%= f.fields_for :tags do |b| %>
          <div class="col-md-6">
            <%= b.text_field :tagname, class: 'form-control' %>
          </div>
          
        <% end %>
      

      <div>
    <%= f.label :protections, "Users to be shared" %>
    <% if @upload.protections.first %>
      <%= f.fields_for :protections do |c| %>
        <%= c.email_field :sharedid, class: 'form-control' %>
      <% end %>
    <% else %>
        <p> Nothing </p>
    <% end %>
      </div>
      
      <div>  
        <%= f.label :permission %>
        <%= f.collection_select :permission, Upload::PERMISSIONS, :to_s, :to_s, 
         :include_blank => true, :selected => 'Private', class: 'form-control' %>
     </div> 
     
        <%= f.label :url, "URL" %>      
        <%= f.url_field :url, class: 'form-control' %>


        <%= f.label :Description %>
        <%= f.text_area :description, placeholder: "Enter description of microstructure(s)", :row => 5, class: 'form-control' %>
        
        
      <%= f.submit "Update your submission", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/uploads/index.html.erb
<p id="notice"><%= notice %></p>



<head>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    
    <br>
    <br>
    
    <div class="container-fluid"  style="padding-left: 0px; padding-right: 0px;">
      <div class="row">

      <% if false %>
        <nav class="col-lg-3">
            <ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="0">
            <li><%= link_to "New Submission",   new_upload_path %></li>
            <li><%= link_to "My Submission",   uploads_mysubmission_path %></li>
            <li><%= link_to "Shared with me",   uploads_sharedtome_path %></li>
            <li class="active"><%= link_to "Search Microgram", uploads_search_path %></li>
            </ul>
        </nav>
      <% end %>

        <div class="col-lg-9">
          <h1 align="center">Search The World of Microgram</h1>
        </div>
      </div>
    </div>
    
    
    <br>
    <br>
    
<!for commenting/>
<% if false %>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= upload.user %></td>
        <td><%= link_to 'Show', upload %></td>
        <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
        <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% end %>

app/views/uploads/mysubmission.html.erb
<br>
<br>
<h1 style="text-align:center">All your awesome submissions.</h1>
<br>

<% eachone = Array.new %>
<% eachone= @all_submission.ids %>

<br>
<br>
<% eachone.each do |a| %>
    <div class="col-sm-5 submission_card" style="height:160px; width:160px">
  


        <p style="text-align:center">

            <% if (@all_submission.find(a).images.first && @all_submission.find(a).tags.first)  %>
                <%= link_to(image_tag(@all_submission.find(a).images.first.image(:small)), upload_path(a) ) %></p>
                <%= @all_submission.find(a).tags.first.tagname %> <br>
                <font size="1">
                Created at : <%= @all_submission.find(a).created_at.to_date %>
                </font>
            <% else %>
                <%= link_to "There is a submission but No images", upload_path(a) %>
            <% end %>


    
    </div>
<% end %>

app/views/uploads/new(previousdf).html.erb
<!%= render 'form' %>

<!%= link_to 'Back', uploads_path %>

<html lang="en">
    
<head>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
   <br>
   <br>
    
    
    <div class="container-fluid"  style="padding-left: 0px; padding-right: 0px;">
      <div class="row">
        <nav class="col-lg-3">
            <ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="0">
            <li class="active"><%= link_to "New Submission",   new_upload_path %></li>
            <li><%= link_to "My Submissions",   new_upload_path %></li>
            <li><%= link_to "Shared with me",   new_upload_path %></li>
            <li><%= link_to "Search Microgram", uploads_path %></li>
            </ul>
        </nav>
    

        <div class="col-lg-9">
            <h1 align="center">Share your awesome images !</h1>
    
        <br>
        <div id="content">
            <%= form_for (@upload), html: { multipart: true, class: "dropzone", id: "my-dropzone" } do |f| %>
            
                <div class="dz-message needsclick">
                    <h3> Drop microstructure(s) here</h3> 
                    or <strong>Click</strong> to upload
                </div>

                <div class="fallback">
                    <%= f.file_field :image %>
                    <!%= f.submit "Upload the image" %>
                </div>
                
            </div>
        <br>
        <br>
        
       
        <div class="container">
          <form class="form-horizontal">
            <div class="form-group">
            <label class="control-label col-lg-1" for="tag" align="left">Tags:</label>
              <div class="col-lg-2">
                <input type="tag" class="form-control" id="tag" placeholder="Enter a tag"></input>
              </div>
              <div class="col-lg-2">
                <input type="tag" class="form-control" id="tag" placeholder="Enter a tag"></input>
              </div>
             <div><span class="glyphicon glyphicon-plus-sign"></span></div>
            </div> 
                

            
            <div class="form-group">
              <label class="control-label col-lg-1" for="description">Description:</label>
              <div class="col-lg-7">
                <%= f.text_area :description, placeholder: "Enter description of microstructure(s)", :row => 5 %> 
              </div>

            </div>
            <br>
            <br>
            <br>

            <div class="form-group">
              <label class="control-label col-lg-1" for="url">URL:</label>
              <div class="col-lg-7">
                <input type="url" class="form-control" id="url" placeholder="Enter link to research"></input>
              </div>
            </div>
            
            <div class="form-group">
              <div class="col-lg-offset-1 col-lg-4">
                <br>
                <button type="submit" "POST" class="btn btn-primary">Submit</button>
              </div>
            </div>
        </div>
            <% end %>
        </div>
       </div>
     </div>
</body>

</html>

app/views/uploads/new.html.erb
<% provide(:title, 'Submission') %>
<br>
<br>
<h1 style="text-align:center">Share your awesome microstructures !</h1>
<br>
<br>
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @upload, :html => { :multipart => true } do |f| %>
    
    <%= f.label :images, "Image Files" %>
    <%= f.file_field @upload.images.build, multiple: true, name: "upload[images_attributes][][image]", class: 'form-control' %>

        <br>
        <%= f.label :tags, "Tags" %>
        <br>
        <%= f.fields_for :tags do |b| %>
          <% if b.object.new_record? %>
          <div class="col-md-6">
          <%= b.text_field :tagname, class: 'form-control' %>
          </div>
          <% end %>
        <% end %>
      
      
      <br>
      <%= f.label :protections, "Users to be shared" %>
      <%= f.fields_for :protections do |c| %>
        <% if c.object.new_record? %>
        <%= c.email_field :sharedid, class: 'form-control' %>
        <% end %>
      <% end %>
      
    
        <%= f.label :permission %>
        <%= f.collection_select :permission, Upload::PERMISSIONS, :to_s, :to_s, 
         :include_blank => true, :selected => 'Private', class: 'form-control' %>
         
        <%= f.label :url, "URL" %>      
        <%= f.url_field :url, class: 'form-control' %>


        <%= f.label :Description %>
        <%= f.text_area :description, placeholder: "Enter description of microstructure(s)", :row => 5, class: 'form-control' %>
        
        
      <%= f.submit "Submit your images", class: "btn btn-primary" %>
    <% end %>
</div>
</div>

app/views/uploads/new.html_previous.erb
<% provide(:title, 'Submission') %>
<br>

<h1>Submission</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@upload, :html => {:multipart => true}) do |f| %>

     <%= f.label :images, "Image Files" %>    
      <%= f.fields_for :images do |a| %>
        <% if a.object.new_record? %>
        <%= a.file_field :image, class: 'form-control' %>
      <% end %>
      <% end %>

      

      <%= f.label :tags, "Tags" %> 
      <%= f.fields_for :tags do |b| %>
        <% if b.object.new_record? %>
        <%= b.text_field :tagname, class: 'form-control' %>
        <% end %>
      <% end %>
      
      <%= f.label :protections, "Users to be shared" %> 
      <%= f.fields_for :protections do |c| %>
        <% if c.object.new_record? %>
        <%= c.text_field :sharedid, class: 'form-control' %>
        <% end %>
      <% end %>
      
    
        <%= f.label :permission %>
        <%= f.collection_select :permission, Upload::PERMISSIONS, :to_s, :to_s, 
         :include_blank => true, :selected => 'Private', class: 'form-control' %>
         
        <%= f.label :url, "URL" %>      
        <%= f.url_field :url, class: 'form-control' %>


        <%= f.label :Description %>
        <%= f.text_area :description, placeholder: "Enter description of microstructure(s)", :row => 5, class: 'form-control' %>
        
        
      <%= f.submit "Submit your images", class: "btn btn-primary" %>
    <% end %>
</div>
</div>

app/views/uploads/new_dropzone.html.erb
<h1>Submission</h1>


    <%= form_for @upload, :html => {:multipart => true, class: "dropzone"} do |f| %>
     
      <div class="dz-preview"></div> 
      <div class="fallback">
      <%= f.fields_for :images do |a| %>
        <%= f.file_field :image, multiple: true %>
      <% end %>
      </div>
 
      <%= f.label :tags, "Tags" %> 
      <%= f.fields_for :tags do |b| %>
        <% if b.object.new_record? %>
        <%= b.text_field :tagname, class: 'form-control' %>
        <% end %>
      <% end %>
      
      
      <%= f.label :protections, "Users to be shared" %> 
      <%= f.fields_for :protections do |c| %>
        <% if c.object.new_record? %>
        <%= c.text_field :sharedid, class: 'form-control' %>
        <% end %>
      <% end %>
      
    
        <%= f.label :permission %>
        <%= f.collection_select :permission, Upload::PERMISSIONS, :to_s, :to_s, 
         :include_blank => true, :selected => 'Private', class: 'form-control' %>
         
        <%= f.label :url, "URL" %>      
        <%= f.url_field :url, class: 'form-control' %>


        <%= f.label :Description %>
        <%= f.text_area :description, placeholder: "Enter description of microstructure(s)", :row => 5, class: 'form-control' %>
        <div style="text-align:center">
        <%= link_to "Submit your images", @upload, id: "sub_button", class: "btn btn-primary" %>
        </div>
      
     <% end %>    
 

app/views/uploads/new_nayan.html.erb
<html lang="en">
    
<head>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
   <br>
   <br>
    
        <div class="col-lg-9">
            <h1 align="center">Share your awesome images !</h1>
    
        <br>
        <div id="content">
            <%= form_for @upload, html: { multipart: true, class: "dropzone", id: "my-dropzone" } do |f| %>
            
                <div class="dz-message needsclick">
                    <h3> Drop microstructure(s) here</h3> 
                    or <strong>Click</strong> to upload
                </div>
                    
            
                <div class="fallback">
                    <%= f.file_field :image %>
                    <!%= f.submit "Upload the image" %>
                </div>
            <% end %>
            </div>
        <br>
        <br>
        
       
        <div class="container">
          <form class="form-horizontal">
            <div class="form-group">
              <label class="control-label col-lg-1" for="tag" align="left">Tags:</label>
              <div class="col-lg-2">
                <input type="tag" class="form-control" id="tag" placeholder="Enter a tag"></input>
              </div>
              <div class="col-lg-2">
                <input type="tag" class="form-control" id="tag" placeholder="Enter a tag"></input>
              </div>
             <div><span class="glyphicon glyphicon-plus-sign"></span></div>
            </div>
            <div class="form-group">
              <label class="control-label col-lg-1" for="description">Description:</label>
              <div class="col-lg-7">
                <textarea type="desc" class="form-control" id="desc" placeholder="Enter description of microstructure(s)" rows=5></textarea>
              </div>
              
            </div>
            <div class="form-group">
              <label class="control-label col-lg-1" for="url">URL:</label>
              <div class="col-lg-7">
                <input type="url" class="form-control" id="url" placeholder="Enter link to research"></input>
              </div>
            </div>
            <div class="form-group">
              <div class="col-lg-offset-1 col-lg-4">
                <button type="submit" class="btn btn-default">Submit</button>
              </div>
            </div>
        </div>

        </div>
       </div>
     </div>
</body>
    
    
</html>

app/views/uploads/new_temp2.html.erb
<br>
<br><br>
<br><br>
<br><br>
<br>
<div class="fallback">
<form id="new_upload", class="dropzone">
  <div class="dz-preview"></div>  <!-- this is were the previews should be shown. -->

  <!-- Now setup your input fields -->
  <input type="text" name="upload[tags_attributes][0][tagname]" id="upload_tags_attributes_0_tagname" />
  <input type="text" name="upload[tags_attributes][1][tagname]" id="upload_tags_attributes_1_tagname" />

  <button type="submit">Submit data and files!</button>
</form>
<div>

app/views/uploads/search.html.erb
<br>
<body>
<h1 style="text-align:center">Explore Microgram</h1>
<div style="text-align:center; margin-top: 50px">
    <%= form_tag(uploads_search_path, :method => "get", id: "search-form", style:"overflow: auto;") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Microstructures" %>
    <br>
    <%= image_submit_tag (asset_path('search_icon.png', width: "20", height: "20")), id: "search_btn" %>
    <% end %>
</div>

<% if @tags.present? %>
    <% @ids.uniq.each do |id| %>
        <% if Upload.find(id).permission == "Public" %>
            <div class="col-sm-5 submission_card" style="height:160px; width:160px">
            <%#= link_to "Image", upload_path(id) %>
            <%#= image_tag Upload.find(id).images.first.image(:small) %>
            <%= link_to(image_tag(Upload.find(id).images.first.image(:small)), upload_path(id) ) %>
            <%= Upload.find(id).tags.first.tagname %> <br>
             <%#= params[:search] %>  
            <font size="1">
            Created at : <%= Upload.find(id).created_at.to_date %>
            </font>
            </div>
        <% end %>
    <% end %>
<% end %>

</body>

app/views/uploads/sharedToMe.html.erb
<br>
<br>
<br>
<h1 style="text-align:center">Your collaborators have shared these !</h1>

<br>
<br>
<br>

    <% if @shared.nil? %>
        <h3> There are no images shared with you! </h3>
    <% else %>
       
        <% @shared.each do |a|%>
            <div class="col-sm-5 submission_card"  style="height:200px; width:200px">        
                <% user = Upload.find(a).user_id %>
                    
                    <div style="text-align:center">
                        <%= link_to(image_tag(Upload.find(a).images.first.image(:small)), upload_path(a) ) %>
                    </div>
                    <%= Upload.find(a).tags.first.tagname %> <br>
                    <font size="1">
                    Shared by: <br>
                    <%= User.find(user).email %>
                    </font>
            </div>
            
        <% end %>
    <% end %>

app/views/uploads/show.html.erb
<br>


<h1 style="text-align:center">This Submission</h1>
<br>
    <div  style="overflow:auto">   
      <% @upload.images.all.each do |a| %>
    <div class="col-sm-5 submission_card" style="height:160px; width:160px">
      <%= image_tag a.image.url(:small) %>
    </div>
      <% end %>
    </div>
    <br>
    <div>     
          <p>
            <li class="tags"> Tags:  </li>
          <% @upload.tags.all.each do |b| %>
              <li class="tags">  <%= link_to b.tagname, uploads_search_path(:search => b.tagname) %></li>
          <% end %>
          </p> 
          

    
    <p class="tagsss"> Description : <%= @upload.description %> </p>
    <p class="tagsss"> Created by : <%= @upload.user.name %> (<%= @upload.user.email %> )  </p>
    <p class="tagsss"> Permission : <%= @upload.permission %></p>
    
    <br>


       

		  
		  <br><br>
		  <% if current_user == @upload.user %>
		  <h4>	<%= link_to "Edit", edit_upload_path(@upload) %></h4>
		  <% end %>
    </div>