config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home'
  get 'password_resets/new'
  get 'password_resets/edit'
  
  get   '/uploads/mysubmission', to: 'uploads#mysubmission'
  get   '/uploads/sharedtome', to: 'uploads#sharedToMe'
  get   '/uploads/search', to: 'uploads#search'
  #post  '/uploads/search', to: 'uploads#search'
  get   '/uploads/search(.:format)', to: 'uploads#search'
  post  '/uploads/search(.:format)', to: 'uploads#search'


  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  resources :users
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :uploads, only: [:new, :create, :update, :destroy, :show, :index, :edit]

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="background-color:#E2F0F666">
  <div class="container">
    <%= link_to "Microgram", '/', :style=>"text-decoration: none; font-size: 2em; color: white", :class=>"navbar-header page-scroll logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <!--<li><#%= link_to "Home",   '/' %></li>-->
        <!--<li><%#= link_to "Sign up",   signup_path %></li>-->
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
    <!--<div class="container-fluid"  style="padding-left: 0px; padding-right: 110px; float:left">-->
      <div id="sidebar" class="row" style="float:left; height:1500px; width: 230px; text-align:center">
        <nav class="col-lg-3" style="width: 230px; margin-top: 30px">
            <ul class="nav nav-pills nav-stacked"  data-offset-top="0">
            <li><%= link_to "New Submission", new_upload_path %></li>
            <li><%= link_to "My Submission",   uploads_mysubmission_path %></li>
            <li><%= link_to "Shared with me",   uploads_sharedtome_path %></li>
            <li><%= link_to "Search Microgram",  uploads_search_path %></li>
            </ul>
        </nav>
      </div>
      
    <!--</div>-->

app/views/layouts/application.html.erb
<html>
<head>
  <title>Microgram</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/layouts/something.html.erb
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/sidebar' %>


    <div class="container">

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>

    </div>
    
  </body>
</html>